# Generated by Django 5.2.10 on 2026-01-29 16:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), 
                ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('SPORT', 'Sport'), 
                ('HATCHBACK', 'Hatchback')], default='SUV', max_length=20)),
                ('year', models.IntegerField(default=2023, 
                validators=[django.core.validators.MinValueValidator(2015), 
                django.core.validators.MaxValueValidator(2023)])),
                ('created_at', 
                models.DateTimeField(default=django.utils.timezone.now)),
                ('car_make', 
                models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
                to='djangoapp.carmake')),
            ],
        ),
    ]
